SCAM_PATTERNS = {
    "upi_fraud": [
        "Your UPI account has been blocked verify now",
        "Send Rs 1 to verify your UPI ID immediately",
        "Congratulations you received Rs 50000 in UPI",
        "Your PhonePe account will be deactivated",
        "UPI payment failed click to retry cashback",
        "Your bank account linked to UPI needs update",
        "You have won a UPI cashback reward enter PIN",
        "Urgent UPI KYC update required immediately",
    ],
    "bank_phishing": [
        "Dear customer your SBI account will be blocked",
        "Your ATM card has been blocked call immediately",
        "Update your KYC or your account will be closed",
        "Your account shows suspicious activity verify",
        "OTP required share it with our bank executive",
        "Your credit card limit upgraded click activate",
        "Unauthorized login detected verify net banking",
        "Your CIBIL score dropped click to fix now",
    ],
    "otp_scam": [
        "Please share the OTP received on your mobile",
        "Our executive needs OTP to process your request",
        "Enter OTP to claim your prize money transfer",
        "Share OTP to verify identity for refund",
        "OTP needed to complete your KYC verification",
        "Bank executive needs OTP to unblock account",
        "Share OTP to receive your cashback reward",
        "Verify OTP to prevent account suspension",
    ],
    "lottery_prize": [
        "You have won 25 lakh rupees in lucky draw",
        "You are selected for KBC prize contact us",
        "Your mobile number won grand prize pay fee",
        "Amazon Flipkart lucky winner special prize",
        "You have won free iPhone pay shipping charges",
        "Government of India relief fund Rs 2 lakh",
        "Congratulations lottery winner claim reward",
        "You won international sweepstakes contact now",
    ],
    "job_scam": [
        "Work from home earn Rs 50000 no experience",
        "Data entry job earn Rs 500 per hour online",
        "Selected for job at TCS pay registration fee",
        "Like subscribe YouTube videos earn daily",
        "Invest Rs 5000 earn Rs 50000 in 7 days",
        "Part time opportunity earn from mobile daily",
        "Guaranteed income working from home apply now",
        "Online job no qualification needed high salary",
    ],
    "romance_scam": [
        "Foreign national stranded airport need help",
        "I have feelings want to send gift from abroad",
        "Soldier doctor working abroad need financial",
        "Account blocked abroad send money return double",
        "We met online trust you help emergency transfer",
        "Customs holding my package need fee payment",
        "Fell in love want to meet need travel money",
        "Inherited money abroad need your bank details",
    ],
    "investment_scam": [
        "Guaranteed returns 40 percent per month",
        "Join trading group earn daily profits zero risk",
        "Crypto investment opportunity double in 30 days",
        "SEBI registered advisor guarantees stock profit",
        "Refer friends earn passive income every day",
        "Secret trading strategy never loses money",
        "Invest now limited spots available high returns",
        "Bitcoin investment multiply money guaranteed",
    ],
    "deepfake_impersonation": [
        "This is your son calling from different number",
        "Calling from police station relative arrested",
        "Family member accident transfer money treatment",
        "Bank manager calling verify account details now",
        "CBI ED calling you are under investigation pay",
        "Your relative in hospital needs money urgently",
        "Government official calling verify your Aadhaar",
        "This is your boss calling need urgent transfer",
    ]
}

HIGH_RISK_KEYWORDS = [
    "otp", "share otp", "enter otp", "pin",
    "cvv", "password", "account blocked",
    "account suspended", "account deactivated",
    "verify immediately", "verify now",
    "click here", "click link", "urgent",
    "act now", "limited time", "expires soon",
    "claim now", "claim reward", "free money",
    "transfer money", "send money", "wire transfer",
    "arrest warrant", "fir", "police case",
    "court notice", "legal action", "cybercrime",
    "aadhaar blocked", "aadhaar update",
    "kyc update", "kyc expired", "kyc pending",
    "kyc verification", "sim blocked",
    "lucky winner", "selected winner", "chosen",
    "processing fee", "registration fee",
    "advance payment", "security deposit",
    "double your money", "guaranteed profit",
    "risk free", "zero risk", "100 percent return",
    "blocked in 24 hours", "suspended account",
    "arrest", "arrested", "police", "jail", "fine", 
    "cbi", "upi", "rupees", "bank account", "suspicious activity",
    "different number", "send me", "lost my phone", "new number", "emergency"
]

SUSPICIOUS_URL_PATTERNS = [
    "bit.ly", "tinyurl.com", "t.co", "shorturl",
    "rebrand.ly", "cutt.ly", "tiny.cc", "is.gd",
    "v.gd", "rb.gy", "ow.ly", "buff.ly",
    ".xyz", ".tk", ".ml", ".ga", ".cf",
    ".gq", ".pw", ".top", ".click",
    "login-", "verify-", "update-", "secure-",
    "account-", "banking-", "kyc-", "otp-",
    "pin-", "claim-", "prize-", "winner-",
    "reward-", "lucky-", "free-money",
]
